openapi: 3.0.0
info:
  title: Impulse Wellness API
  version: 1.0.0
paths:
  /api/health-metrics:
    get:
      summary: Get health metrics
      responses:
        '200':
          description: Health metrics
    post:
      summary: Save health metrics
      responses:
        '201':
          description: Metrics saved
  /api/programs:
    get:
      summary: Get wellness programs
      responses:
        '200':
          description: List of programs
